acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: acend
      replicaCount: 2
      image:
        repository: quay.io/acend/openshift-operations-training
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        secretOverride: acend-wildcard
        appname: openshift-operations
        domain: training.acend.ch
    - 
      name: puzzle
      replicaCount: 2
      image:
        repository: quay.io/acend/openshift-operations-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-puzzle"
      ingress:
        secretOverride: acend-wildcard
        appname: openshift-operations
        domain: training.puzzle.ch

nameOverride: "openshift-operations"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
