apiVersion: v1
data:
  config.yaml: |
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra"
        effect: NoSchedule
    prometheusK8s:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
    grafana:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra"
        effect: NoSchedule
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra"
        effect: NoSchedule
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra"
        effect: NoSchedule
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra"
        effect: NoSchedule
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra"
        effect: NoSchedule
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra"
        effect: NoSchedule
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"alertmanagerMain:\n  nodeSelector:\n    node-role.kubernetes.io/infra: \"\"\n  tolerations:\n  - key: \"node-role.kubernetes.io/infra\"\n    effect: NoSchedule\nprometheusK8s:\n  nodeSelector:\n    node-role.kubernetes.io/infra: \"\"\n  tolerations:\n  - key: node-role.kubernetes.io/infra\n    effect: NoSchedule\ngrafana:\n  nodeSelector:\n    node-role.kubernetes.io/infra: \"\"\n  tolerations:\n  - key: \"node-role.kubernetes.io/infra\"\n    effect: NoSchedule\nk8sPrometheusAdapter:\n  nodeSelector:\n    node-role.kubernetes.io/infra: \"\"\n  tolerations:\n  - key: \"node-role.kubernetes.io/infra\"\n    effect: NoSchedule\nkubeStateMetrics:\n  nodeSelector:\n    node-role.kubernetes.io/infra: \"\"\n  tolerations:\n  - key: \"node-role.kubernetes.io/infra\"\n    effect: NoSchedule\ntelemeterClient:\n  nodeSelector:\n    node-role.kubernetes.io/infra: \"\"\n  tolerations:\n  - key: \"node-role.kubernetes.io/infra\"\n    effect: NoSchedule\nopenshiftStateMetrics:\n  nodeSelector:\n    node-role.kubernetes.io/infra: \"\"\n  tolerations:\n  - key: \"node-role.kubernetes.io/infra\"\n    effect: NoSchedule\nthanosQuerier:\n  nodeSelector:\n    node-role.kubernetes.io/infra: \"\"\n  tolerations:\n  - key: \"node-role.kubernetes.io/infra\"\n    effect: NoSchedule\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"cluster-monitoring-config","namespace":"openshift-monitoring"}}
  creationTimestamp: "2021-04-16T07:33:22Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2021-04-16T07:33:22Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:config.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-16T07:40:23Z"
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  resourceVersion: "1896941"
  selfLink: /api/v1/namespaces/openshift-monitoring/configmaps/cluster-monitoring-config
  uid: 9028758b-f19b-4544-af7a-1be7e4b99998
